---
title: "Lab06"
author: "Spencer Johnson"
date: "2025-02-20"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## A. Probabilities of composite events

- 1. What is the probability that it does NOT snow on two consecutive days? 
      - `r 0.7 * 0.7` #multiplying the chances of NOT snow by the two days
      
- 2. What is the probability that it does NOT snow on 10 consecutive days?
      - `r round(0.7^10, 3)`
      
- 3. What is the probability that it does NOT snow on n consecutive days?
      - 0.7^n
      
- 4. What is the probability that it snows on the nth day, and not on any day before that?
      - 0.3 * (1-0.3)^n-1
      
- 5. The sum of the two dice is 7 and both coins show heads.
      -`r 0.25 * 0.16` #multiplying the (0.5 * 0.5) chance of the 2 coins by the odds of getting the 7 with two dice, of which there are #6 ways out of 36 possible combinations - 1/6
      
- 6. Either:
- There is exactly one head and the sum of the dice is more than 3, or
- There are no heads and the sum of the dice is less than 6
      -`r (0.916 * (0.5 * 0.5)) + ((0.5 * 0.5) * 0.2778)`
      
- 7. C1 is heads, C2 is either heads or tails, D1 is 3, and D2 is less than 5.
      -`r 0.5 * 1 * 1/6 * 0.66`
      
## B. Conditional probabilities and independence - see the conditional probability formula

- 1. `r 0.5 * 0.091`

- 2. If they're **not** independent, then the outcome of one depends on the outcome of another.

- 3. `r 0.2 * 0.091` - A and B are not independent because we're **told** the A depends on B

- 4. `r (0.2 * 0.091)/0.5` 

## C. Probability of sequences

- 1. What is the probability that a given monkey types the word “BANANA”?
      - `r 0.385^6` #odds of getting the right letter 6 times in a row - 1/26
      
- 2. Hence, approximately how many monkeys in a room are required to get the word BANANA typed?
      - `r 1/(0.385^6)` #Ivana told use to just put this and we can try to understand at a later date.
      
Now, instead of monkeys, imagine a large number of people flipping a fair coin six times each.

- 1. What is the probability that a given person gets the sequence “HTTHTT”?
      - `r 0.5^2 * (1-0.5)^4` 
      
- 2. Now, assume that the coin is unfair, such that a heads appears with a probability p, and thus tails
appears with a probability q = 1 − p What is the probability that a given person gets the sequence
“HTTHTT”?
      - p^2 * q^4
      
- 3. What is the probability that a given person gets the sequences “THTHTT” with the **unfair** coin?
      - p^2 * q^4
      
- 4. With the unfair coin, out of 10,000 people, approximately how many will get the sequence “HTTHTT”?
How many will get the sequence “THTHTT”?
      - 10,000 * (p^2 * q^4) It will be the same for both because it's the same number of H and T in different sequences
      
- 5. Convince yourself that each re-arrangement of “HTTHTT” will be obtained by the same number of
people as in C.4 (i.e., each rearrangement has the same probability of appearing). How many unique
re-arrangements of “HTTHTT” are there?
      - choose(6, 2)
      
- 6. Hence, what is the total probability of getting 2 heads and 4 tails in the process (arranged in any
order)?
      - choose(6, 2) * (p^2 * q^4)

